# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

os:
  - osx
  - linux

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true" 

script: "./travis-tool.sh run_tests"

r_packages:
  - XML
  - RCurl
  - plyr
  - reshape2
  - lubridate

after_script:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
